all:
  children:
    db:
      hosts:
        rpi4-db:
          ansible_host: 10.0.0.11
    api:
      hosts:
        rpi4-api:
          ansible_host: 10.0.0.13 
    app:
      hosts:
        rpi4-app:
          ansible_host: 10.0.0.16
