all:
  children:
    db:
      hosts:
        rpi4-db:
          ansible_host: 192.168.1.184
    api:
      hosts: {}
      # rpi4-api:
      #   ansible_host: 10.0.0.13  # TODO: set once rpi4-api exists
    app:
      hosts: {}
      # rpi4-app:
      #   ansible_host: 10.0.0.16  # TODO: set once rpi4-app exists
