---
api_repo_version: main
api_app_user: sensors-api
api_app_group: sensors-api
api_app_dir: /srv/sensors-api/app
api_env_file: /etc/sensors-api/api.env
api_python_version: "3.14"
api_uvicorn_port: 8000
