---
- import_tasks: user.yml
- import_tasks: uv_install.yml
- import_tasks: grafana.yml
- import_tasks: apps.yml
- import_tasks: rtl433_build.yml
- import_tasks: rtl433_blacklist.yml
- import_tasks: rtl433_service.yml
