---
- name: Ensure sensors-app group exists
  ansible.builtin.group:
    name: "{{ app_group }}"
    system: true
    state: present

- name: Ensure sensors-app system user exists
  ansible.builtin.user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: "{{ app_base_dir }}"
    create_home: true
    state: present

- name: Ensure the apps base directory exists
  ansible.builtin.file:
    path: "{{ app_base_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
