---
api_repo_url: https://github.com/jameslittle3369/sensors-backend-fastapi.git
api_repo_version: main
api_app_user: sensors-api
api_app_group: sensors-api
api_app_dir: /srv/sensors-api/app
api_env_file: /etc/sensors-api/api.env
api_python_version: "3.14"
api_uvicorn_port: 8000
api_owserver_url: "http://10.0.0.188/details.xml"
api_dyson_host: "10.0.0.17"

ufw_extra_ports:
  - port: 80
    proto: tcp
